name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
        cd /home/ubuntu/LastLaunch
        git pull
        chmod +x deploy.sh
        ./deploy.sh

